### ISSUE TITLE
need pie-update-all-packages

### ISSUE THREAD

**Issue by CarefreeLee** [zbelial/pie#7]
# 背景
有时需要更新 packages ,图方便想一次更新完所有包

# 需求
 update-all-packages  的函数, 并且能知道那些包被更新了,如果可以的话能输出历史记录就好了

感谢

**Comment by zbelial** [comment]
知道哪些包被更新了有点复杂，我没理解错的话你的意思是如果只有远程仓库跟本地不一致，才算是需要更新？

**Comment by zbelial** [comment]
如果只是不管三七二十一地更新所有包，那比较简单，遍历生成的`pie--packages`，挨个更新就得了。可以记录每个包的更新时间，防止重复更新。

**Comment by CarefreeLee** [comment]
是的,类似跟 git-submodules 更新那样

**Comment by CarefreeLee** [comment]
是否可以增加: 包更新了,输出对应的 url 网址,这样如果想去了解该包更新了什么,可以快速的用 browser-at-point 打开网址看更新详情

**Comment by zbelial** [comment]
检查远程仓库是否比本地更新有点复杂，懒得搞啊，而且我自己没有全量更新包的需求。pie的初衷大概就两点：支持浅克隆、然后尽量简单。
如果是不管远程有没有更新，都update一遍，那还可以考虑。

**Comment by CarefreeLee** [comment]
呃,就是你说的那样啊
抱歉,可能你考虑的细节比较多

> 如果只是不管三七二十一地更新所有包，那比较简单，遍历生成的`pie--packages`，挨个更新就得了。可以记录每个包的更新时间，防止重复更新。

**Comment by zbelial** [comment]
推到新分支update-all了，我没想更新所有包所以就完全没测试，脑子里测试了一下，应该没啥大问题，你可以试试看。有问题就自立更生吧。

**Comment by CarefreeLee** [comment]
Work.
